export const courses = [
    {value: 'All courses', label: 'All courses'},
    { value: 'CSCA08', label: 'CSCA08 - Introduction to Computer Science I' },
    { value: 'CSCA20', label: 'CSCA20 - Introduction to Programming' },
    { value: 'CSCA48', label: 'CSCA48 - Introduction to Computer Science II' },
    { value: 'CSCA67', label: 'CSCA67 - Discrete Mathematics' },
    { value: 'CSCB07', label: 'CSCB07 - Software Design' },
    { value: 'CSCB09', label: 'CSCB09 - Software Tools and Systems Programming' },
    { value: 'CSCB36', label: 'CSCB36 - Introduction to the Theory of Computation' },
    { value: 'CSCB58', label: 'CSCB58 - Computer Organization' },
    { value: 'CSCC01', label: 'CSCC01 - Principles of Programming Languages' },
    { value: 'CSCC09', label: 'CSCC09 - Operating Systems' },
    { value: 'CSCC10', label: 'CSCC10 - The Internet and Emerging Technologies' },
    { value: 'CSCC11', label: 'CSCC11 - Introduction to Machine Learning and Data Mining' },
    { value: 'CSCC24', label: 'CSCC24 - Principles of Programming Languages' },
    { value: 'CSCD03', label: 'CSCD03 - Social and Information Networks' },
    { value: 'CSCD27', label: 'CSCD27 - Computer and Network Security' },
    { value: 'CSCD37', label: 'CSCD37 - Computer Graphics' },
    { value: 'CSCD54', label: 'CSCD54 - Computer Networks' },
    { value: 'CSCD58', label: 'CSCD58 - Distributed Systems' },
    { value: 'CSCD70', label: 'CSCD70 - Software Engineering' },
    { value: 'CSCD71', label: 'CSCD71 - Human-Computer Interaction' },
    { value: 'CSCD72', label: 'CSCD72 - Database Systems' },
    { value: 'CSCD84', label: 'CSCD84 - Artificial Intelligence' },
    { value: 'CSCD85', label: 'CSCD85 - Introduction to Game Programming' },
    { value: 'CSCD88', label: 'CSCD88 - Advanced Topics in Computer Science' },
    { value: 'MATA22', label: 'MATA22 - Linear Algebra I' },
    { value: 'MATA31', label: 'MATA31 - Calculus II' },
    { value: 'MATA37', label: 'MATA37 - Differential Equations' },
    { value: 'MATB24', label: 'MATB24 - Calculus III' },
    { value: 'MATB41', label: 'MATB41 - Techniques of the Calculus of Several Variables I' },
    { value: 'MATB42', label: 'MATB42 - Techniques of the Calculus of Several Variables II' },
    { value: 'MATC12', label: 'MATC12 - Introduction to Combinatorics' },
    { value: 'MATC13', label: 'MATC13 - Introduction to Number Theory' },
    { value: 'MATC44', label: 'MATC44 - Introduction to Analysis' },
    { value: 'MATC53', label: 'MATC53 - Ordinary Differential Equations' },
    { value: 'MATC55', label: 'MATC55 - Complex Variables' },
    { value: 'MATD01', label: 'MATD01 - Introduction to Topology' },
    { value: 'MATD20', label: 'MATD20 - Graph Theory' },
    { value: 'MATD26', label: 'MATD26 - Mathematical Logic' },
    { value: 'MATD35', label: 'MATD35 - Introduction to Mathematical Logic' },
    { value: 'MATD43', label: 'MATD43 - Real Analysis I' },
    { value: 'MATD44', label: 'MATD44 - Real Analysis II' },
    { value: 'MATD53', label: 'MATD53 - Partial Differential Equations' },
    { value: 'STAB22', label: 'STAB22 - Introduction to Probability' },
    { value: 'STAB52', label: 'STAB52 - Probability and Statistics II' },
    { value: 'STAB57', label: 'STAB57 - Statistics for Science' },
    { value: 'STAC67', label: 'STAC67 - Applied Probability' },
];
